services:
  bookdb:
    container_name: bookdb
    environment:
      MYSQL_ROOT_PASSWORD: root_mysql_password
      MYSQL_DATABASE: BookDB
      MYSQL_USER: user_mysql
      MYSQL_PASSWORD: user_mysql
    restart: always
    ports:
        - "3306:3306"
    volumes:
       - mysql_book:/var/lib/mysql
 
  userdb:
    container_name: userdb 
    environment:
        - ACCEPT_EULA=Y
        - SA_PASSWORD=Anxk12345678
    restart: always
    ports:
        - "1433:1433"  
    volumes:
       - sqlserver_user:/var/opt/mssql

  borrrowingdb:
    container_name: borrrowingdb
    restart: always
    ports:
      - "27018:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=adminMongo123
      - MONGO_INITDB_ROOT_PASSWORD=adminMongo123
      - MONGO_INITDB_DATABASE=BorrrowingDB
    volumes:
      - mongodb_borrrowing:/data/db 

  messagebroker:
    container_name: messagebroker
    hostname: ecommerce-mq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"

  bookservice.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__Database=Server=bookdb;Port=3306;Database=BookDB;User=user_mysql;Password=user_mysql
      - MessageBroker__Host=amqp://ecommerce-mq:5672
      - MessageBroker__UserName=guest
      - MessageBroker__Password=guest
    ports:
      - "6000:8080"
      - "6060:8081"
    depends_on:
      - bookdb
      - messagebroker
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro

  userservice.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__Database=Server=userdb,1433;Database=UserDb;User Id=sa;Password=Anxk12345678;Encrypt=False;TrustServerCertificate=True
    ports:
      - "6001:8080"
      - "6061:8081"
    depends_on:
      - userdb
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro

  borrowingservice.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__Database=mongodb://adminMongo123:adminMongo123@borrrowingdb:27017/BorrrowingDB
      - MessageBroker__Host=amqp://ecommerce-mq:5672
      - MessageBroker__UserName=guest
      - MessageBroker__Password=guest
    ports:
      - "6002:8080"
      - "6062:8081"
    depends_on:
      - borrrowingdb
      - messagebroker
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro

  ocelotapigateway:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
    ports:
      - "6003:8080"
      - "6063:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
